dofile("test/compose.lua")
dofile("test/coroutines.lua")
dofile("test/utils.lua")
dofile("test/telemetry.lua")
dofile("test/power_monitor.lua")
dofile("test/collections.lua")
dofile("test/crafter.lua")
dofile("test/production_line.lua")

print("repository test suite: OK")
