dofile("test/compose.lua")
dofile("test/coroutines.lua")
dofile("test/utils.lua")
dofile("test/telemetry.lua")
dofile("test/power_monitor.lua")
dofile("test/collections.lua")
dofile("test/crafter.lua")
dofile("test/production_line.lua")
dofile("test/query.lua")
dofile("test/visuals.lua")
dofile("src/test/timeline.lua")
dofile("src/test/power_monitor/chart.lua")
dofile("src/test/production_line/chart.lua")

print("repository test suite: OK")
