dofile("test/compose.lua")
dofile("test/coroutines.lua")
dofile("test/storage.lua")
dofile("test/telemetry.lua")
dofile("test/collections.lua")
dofile("test/format.lua")
dofile("test/series.lua")
dofile("test/clock.lua")
dofile("test/query.lua")
dofile("test/power_monitor/chart.lua")
dofile("test/production_line/chart.lua")
dofile("test/timeline.lua")

print("test suite: OK")
